# Generated by Django 5.0.1 on 2024-02-05 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی پروفایل', primary_key=True, serialize=False, unique=True, verbose_name='ای دی پروفایل')),
                ('first_name', models.CharField(blank=True, db_index=True, help_text='اسم را وارد کنید', max_length=20, null=True, verbose_name='اسم')),
                ('image', models.ImageField(blank=True, db_index=True, help_text='عکس', null=True, upload_to='', verbose_name='عکس')),
                ('last_name', models.CharField(blank=True, db_index=True, help_text='فامیلی را وارد کنید', max_length=20, null=True, verbose_name='فامیلی')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='ایمیل خود را وارد کنید', max_length=100, null=True, verbose_name='ایمیل')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('user', models.OneToOneField(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل',
                'ordering': ['created'],
            },
        ),
    ]
