# Generated by Django 5.0.1 on 2024-02-09 11:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_myprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی تیکت', primary_key=True, serialize=False, unique=True, verbose_name='ای دی تیکت')),
                ('ticket_type', models.CharField(choices=[('باز', 'باز'), ('بسته', 'بسته'), ('درحال برسی', 'درحال برسی'), ('پاسخ داده شده', 'پاسخ داده شده')], db_index=True, default='باز', help_text='نوع تیکت', max_length=50, verbose_name='نوع تیکت')),
                ('department_type', models.CharField(blank=True, db_index=True, help_text='دپارتمان\u200cرا\u200cانتخاب\u200cکنید', max_length=40, null=True, verbose_name='دپارتمان\u200cرا\u200cانتخاب\u200cکنید')),
                ('department_ticket_type', models.CharField(blank=True, db_index=True, help_text='نوع دیپارتمنت تیکت', max_length=40, null=True, verbose_name='نوع دیپارتمنت تیکت')),
                ('subject', models.CharField(blank=True, db_index=True, help_text='موضوع تیکت', max_length=250, null=True, verbose_name='موضوع تیکت')),
                ('emergency_type', models.CharField(blank=True, choices=[('کم', 'کم'), ('متوسط', 'متوسط'), ('زیاد', 'زیاد')], db_index=True, default='کم', max_length=30, null=True, verbose_name='نوع ضروری پیام')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('sender_user', models.ForeignKey(help_text='ارسال کننده', on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
            ],
            options={
                'verbose_name': 'تیکت ها',
                'verbose_name_plural': 'تیکت ها',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی تیکت', primary_key=True, serialize=False, unique=True, verbose_name='ای دی تیکت')),
                ('receiver_messager', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='دریافت کننده')),
                ('message_file', models.FileField(blank=True, db_index=True, help_text='فایل', null=True, upload_to='', verbose_name='فایل')),
                ('message', models.TextField(db_index=True, help_text='پیغام', verbose_name='پیغام')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('sender_messager', models.ForeignKey(blank=True, help_text='ارسال کننده', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_messager', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده')),
                ('ticket', models.ForeignKey(blank=True, help_text='تیکت', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیغام ها',
                'verbose_name_plural': 'پیغام ها',
                'ordering': ['created'],
            },
        ),
    ]
