# Generated by Django 5.0.1 on 2024-02-09 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_ticket_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sender_user',
            field=models.ForeignKey(blank=True, help_text='ارسال کننده', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده'),
        ),
    ]
