# Generated by Django 5.0.1 on 2024-02-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_ticket_sender_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_login_now',
            field=models.BooleanField(db_index=True, default=False, help_text='is user login now', verbose_name='is user login now'),
        ),
    ]
