# Generated by Django 5.0.1 on 2024-02-11 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_copon_specialcopon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی فایل', primary_key=True, serialize=False, unique=True, verbose_name='ای دی فایل')),
                ('file_name', models.CharField(blank=True, db_index=True, help_text='نام فایل', max_length=100, null=True, verbose_name='نام فایل')),
                ('part', models.CharField(blank=True, db_index=True, help_text='قسمت', max_length=50, null=True, verbose_name='قسمت')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=False, help_text='فعال است', null=True, verbose_name='فعال است')),
                ('product_file', models.FileField(blank=True, db_index=True, help_text='فایل', null=True, upload_to='', verbose_name='فایل')),
                ('file_link', models.URLField(blank=True, db_index=True, help_text='لینک', null=True, verbose_name='لینک')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('category', models.ForeignKey(blank=True, help_text='دسته بندی', null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'فایل ها',
                'verbose_name_plural': 'فایل ها',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی ویدیو', primary_key=True, serialize=False, unique=True, verbose_name='ای دی ویدیو')),
                ('part', models.CharField(blank=True, db_index=True, help_text='قسمت', max_length=50, null=True, verbose_name='قسمت')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=False, help_text='فعال است', null=True, verbose_name='فعال است')),
                ('video_duration', models.CharField(db_index=True, help_text='دقایق فیلم', max_length=50, verbose_name='دقایق فیلم')),
                ('video_link', models.URLField(blank=True, db_index=True, help_text='لینک', null=True, verbose_name='لینک')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('category', models.ForeignKey(blank=True, help_text='دسته بندی', null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'فیلم ها',
                'verbose_name_plural': 'فیلم ها',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='ProductVoice',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی ویس', primary_key=True, serialize=False, unique=True, verbose_name='ای دی ویس')),
                ('part', models.CharField(blank=True, db_index=True, help_text='قسمت', max_length=50, null=True, verbose_name='قسمت')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=False, help_text='فعال است', null=True, verbose_name='فعال است')),
                ('voice', models.FileField(blank=True, db_index=True, help_text='ویس', null=True, upload_to='', verbose_name='ویس')),
                ('voice_duration', models.CharField(db_index=True, help_text='دقایق ویس', max_length=50, verbose_name='دقایق ویس')),
                ('voice_link', models.URLField(blank=True, db_index=True, help_text='لینک', null=True, verbose_name='لینک')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('category', models.ForeignKey(blank=True, help_text='دسته بندی', null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'ویس ها',
                'verbose_name_plural': 'ویس ها',
                'ordering': ['updated'],
            },
        ),
    ]
