# Generated by Django 5.0.1 on 2024-02-01 14:55

import ckeditor_uploader.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی تصویر', primary_key=True, serialize=False, unique=True, verbose_name='ای دی تصویر')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_show', models.TextField(blank=True, db_index=True, help_text='توضیحات برای نمایش', null=True, verbose_name='توضیحات برای نمایش')),
                ('title', models.CharField(blank=True, db_index=True, help_text='موضوع', max_length=100, null=True, verbose_name='موضوع')),
                ('slug', models.SlugField(blank=True, help_text='اسلاگ', null=True, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=False, help_text='فعال است ؟', null=True, verbose_name='فعال است ؟')),
                ('image', models.ImageField(blank=True, db_index=True, null=True, upload_to='')),
                ('mobile_image', models.ImageField(blank=True, db_index=True, help_text='عکس سایز موبایل', null=True, upload_to='', verbose_name='عکس سایز موبایل')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('left_up_home', models.BooleanField(db_index=True, default=False, help_text='  نمایش درسمت چپ بالا')),
                ('left_down_home', models.BooleanField(db_index=True, default=False, help_text='نمایش درسمت چپ پایین')),
                ('one', models.BooleanField(db_index=True, default=False)),
                ('two', models.BooleanField(db_index=True, default=False)),
                ('three', models.BooleanField(db_index=True, default=False)),
                ('four', models.BooleanField(db_index=True, default=False)),
                ('five', models.BooleanField(db_index=True, default=False)),
                ('writer', models.CharField(blank=True, help_text='نویسنده', max_length=100, null=True, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'مقالات',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
