# Generated by Django 5.0.1 on 2024-02-01 14:55

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی معلم', primary_key=True, serialize=False, unique=True, verbose_name='ای دی معلم')),
                ('name', models.CharField(db_index=True, help_text='نام معلم را ئارد کنید', max_length=50, verbose_name='نام معلم')),
                ('slug', models.SlugField(blank=True, help_text='اسلاگ', null=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', verbose_name='زمان ارتقا')),
            ],
            options={
                'verbose_name': 'معلم ها',
                'verbose_name_plural': 'معلم ها',
                'ordering': ['updated'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی دسته بندی', primary_key=True, serialize=False, unique=True, verbose_name='ای دی دسته بندی')),
                ('ckedit', ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(db_index=True, help_text='نام دسته بندی را وارد کنید', max_length=250, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(blank=True, help_text='اسلاگ', null=True, verbose_name='اسلاگ')),
                ('package_contacts', models.CharField(blank=True, db_index=True, help_text='مخاطبین دوره', max_length=250, null=True, verbose_name='مخاطبین دوره')),
                ('subject', models.TextField(blank=True, db_index=True, help_text='موضوع آموزش', null=True, verbose_name='موضوع آموزش')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='فعال است ؟', verbose_name='فعال است')),
                ('category_duration', models.TimeField(blank=True, db_index=True, help_text='مدت زمان', null=True, verbose_name='مدت زمان')),
                ('session_numbers', models.PositiveIntegerField(blank=True, db_index=True, help_text='تعداد جلسات', null=True, verbose_name='تعداد جلسات')),
                ('description', models.TextField(blank=True, db_index=True, help_text='توضیحات', null=True, verbose_name='توضیحات')),
                ('price', models.FloatField(blank=True, db_index=True, help_text='قیمت', null=True, verbose_name='قیمت')),
                ('show_price', models.FloatField(blank=True, db_index=True, help_text='قیمت اف خورده', null=True, verbose_name='قیمت اف خورده')),
                ('product_type', models.CharField(choices=[('حضوری', 'حضوری'), ('غیرحضوری', 'غیرحضوری'), ('online', 'online')], db_index=True, default='غیرحضوری', help_text='نوع محصول', max_length=10, verbose_name='نوع محصول')),
                ('pre_review', models.URLField(blank=True, db_index=True, help_text='پیش نمایش', null=True, verbose_name='پیش نمایش')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', verbose_name='زمان ارتقا')),
                ('parent', models.ForeignKey(blank=True, help_text='سر دسنه بندی', null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='سر دسنه بندی')),
                ('saves', models.ManyToManyField(blank=True, db_index=True, help_text='سیو شده', to=settings.AUTH_USER_MODEL, verbose_name='سیو شده')),
                ('teacher', models.ForeignKey(blank=True, help_text='مدرس دوره', null=True, on_delete=django.db.models.deletion.PROTECT, to='category.teacher', verbose_name='مدرس دوره')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherFeather',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی ', primary_key=True, serialize=False, unique=True, verbose_name='ای دی ')),
                ('detail', models.TextField(db_index=True, help_text='مشخصات', verbose_name='مشخصات')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', verbose_name='زمان ارتقا')),
                ('teacher', models.ForeignKey(help_text=' معلم', on_delete=django.db.models.deletion.CASCADE, to='category.teacher', verbose_name=' معلم')),
            ],
            options={
                'verbose_name': 'مشخصات مدرس',
                'verbose_name_plural': 'مشخصات مدرس',
                'ordering': ['created'],
            },
        ),
    ]
