# Generated by Django 5.0.1 on 2024-02-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='سر دسنه بندی', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child', to='category.category', verbose_name='سر دسنه بندی'),
        ),
    ]
