# Generated by Django 5.0.1 on 2024-02-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('0', 'pay'), ('1', 'free')], db_index=True, default='0', help_text='نوع دسته بندی', max_length=1, verbose_name='نوع دسته بندی'),
        ),
    ]
