# Generated by Django 5.0.1 on 2024-02-04 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Copon',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی کوپون', primary_key=True, serialize=False, unique=True, verbose_name='ای دی کوپون')),
                ('copone_code', models.CharField(blank=True, db_index=True, help_text='کد تخفیف', max_length=4, null=True, verbose_name='کد تخفیف')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='فعال است ؟', verbose_name='فعال است')),
                ('number', models.PositiveIntegerField(help_text='تعداد', verbose_name='تعداد')),
                ('expire_time', models.DateTimeField()),
                ('off_percent', models.PositiveIntegerField(blank=True, help_text='درصد تخفیف', null=True, verbose_name='درصد تخفیف')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', verbose_name='زمان ارتقا')),
            ],
            options={
                'verbose_name': 'کد های تخفیف',
                'verbose_name_plural': 'کد های تخفیف',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='SpecialCopon',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی  کوپون اختصاصی', primary_key=True, serialize=False, unique=True, verbose_name='ای دی  کوپون اختصاصی')),
                ('copone_code', models.CharField(blank=True, db_index=True, help_text='کد تخفیف', max_length=4, null=True, verbose_name='کد تخفیف')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='فعال است ؟', verbose_name='فعال است')),
                ('off_percent', models.PositiveIntegerField(blank=True, help_text='درصد تخفیف', null=True, verbose_name='درصد تخفیف')),
                ('expired', models.BooleanField(default=False, help_text='منقضی شده', verbose_name='منقضی شده')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', verbose_name='زمان ارتقا')),
                ('user', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کد های  تخفیف اختصاصی',
                'verbose_name_plural': 'کد های  تخفیف اختصاصی',
                'ordering': ['created'],
            },
        ),
    ]
