# Generated by Django 5.0.1 on 2024-02-02 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی دسته بندی', primary_key=True, serialize=False, unique=True, verbose_name='ای دی دسته بندی')),
                ('cart_id_custom', models.CharField(db_index=True, max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی دسته بندی', primary_key=True, serialize=False, unique=True, verbose_name='ای دی دسته بندی')),
                ('quantity', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
