# Generated by Django 5.0.1 on 2024-02-02 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_category_category_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی نظر', primary_key=True, serialize=False, unique=True, verbose_name='ای دی نظر')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='فعال است ؟', verbose_name='فعال است ؟')),
                ('review', models.TextField(db_index=True, help_text='نظر', max_length=200, verbose_name='نظر')),
                ('rating', models.FloatField(blank=True, db_index=True, help_text='ستاره', null=True, verbose_name='ستاره')),
                ('name', models.CharField(blank=True, db_index=True, help_text='نام', max_length=50, null=True, verbose_name='نام')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', verbose_name='زمان ارتقا')),
                ('category', models.ForeignKey(help_text='پکیج', on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='پکیج')),
                ('parent', models.ForeignKey(blank=True, help_text='دسته نظر', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='reviews.reviewrating', verbose_name='دسته نظر')),
                ('user', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظرات',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
