# Generated by Django 5.0.1 on 2024-02-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='review_type',
            field=models.CharField(blank=True, choices=[('0', 'pay'), ('1', 'free')], db_index=True, default='0', help_text='review type', max_length=1, null=True, verbose_name='review type'),
        ),
    ]
