# Generated by Django 5.0.1 on 2024-02-03 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_category_type'),
        ('reviews', '0002_reviewrating_review_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='category',
            field=models.ForeignKey(blank=True, help_text='پکیج', null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='پکیج'),
        ),
        migrations.AlterField(
            model_name='reviewrating',
            name='user',
            field=models.ForeignKey(blank=True, help_text='کاربر', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
