# Generated by Django 5.0.1 on 2024-02-04 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('reviews', '0003_alter_reviewrating_category_alter_reviewrating_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBlog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی  نظر بلاگ', primary_key=True, serialize=False, unique=True, verbose_name='ای دی  نظر بلاگ')),
                ('name', models.CharField(blank=True, db_index=True, help_text='نام', max_length=50, null=True, verbose_name='نام')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='ایمیل', max_length=254, null=True, verbose_name='ایمیل')),
                ('review', models.TextField(blank=True, db_index=True, help_text='نظر', max_length=25, null=True, verbose_name='نظر')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='فعال است ؟', verbose_name='فعال است ؟')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', verbose_name='زمان ارتقا')),
                ('blog', models.ForeignKey(blank=True, help_text='بلاگ', null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.blog', verbose_name='بلاگ')),
                ('parent', models.ForeignKey(blank=True, help_text='دسته نظر', null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviewblog', verbose_name='دسته نظر')),
                ('user', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظرات بلاگ ها',
                'verbose_name_plural': 'نظرات بلاگ ها',
            },
        ),
    ]
