# Generated by Django 5.0.1 on 2024-02-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_reviewblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewblog',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='دسته نظر', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='reviews.reviewblog', verbose_name='دسته نظر'),
        ),
    ]
