# Generated by Django 5.0.1 on 2024-02-04 15:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0002_cartitem_cart'),
        ('category', '0004_copon_specialcopon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeOrderProduct',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی سفارش رایگان', primary_key=True, serialize=False, unique=True, verbose_name='ای دی سفارش رایگان')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('free_category', models.ForeignKey(help_text='دسته بندی رایگان', on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='دسته بندی رایگان')),
                ('user', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارشات پکیج رایگان',
                'verbose_name_plural': 'سفارشات پکیج رایگان',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی سفارش', primary_key=True, serialize=False, unique=True, verbose_name='ای دی سفارش')),
                ('order_custom_id', models.CharField(blank=True, db_index=True, help_text='ای دی', max_length=20, null=True, verbose_name='ای دی')),
                ('name', models.CharField(blank=True, db_index=True, help_text=' نام کاربر', max_length=15, null=True, verbose_name='نام کاربر')),
                ('last_name', models.CharField(blank=True, db_index=True, help_text='نام خانوادگی کاربر', max_length=15, null=True, verbose_name='نام خانوادگی کاربر')),
                ('email', models.EmailField(db_index=True, help_text='ایمیل', max_length=100, verbose_name='ایمیل')),
                ('order_total', models.FloatField(blank=True, db_index=True, help_text='مبلغ پرداخت سفارش', null=True, verbose_name='مبلغ پرداخت سفارش')),
                ('tax', models.FloatField(blank=True, db_index=True, help_text='مبلغ مالیات', null=True, verbose_name='مبلغ مالیات')),
                ('total_after_use_copon', models.FloatField(blank=True, db_index=True, help_text='مبلغ پرداخت بعد از کوپون', null=True, verbose_name='مبلغ پرداخت بعد از کوپون')),
                ('used_copon', models.BooleanField(blank=True, db_index=True, default=False, help_text='از کد تخفیف استفاده کرده', null=True, verbose_name='از کد تخفیف استفاده کرده')),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='New', help_text='وضعیت سفارش', max_length=10, verbose_name='وضعیت سفارش')),
                ('is_ordered', models.BooleanField(db_index=True, default=False, help_text='سفارش انجام شده ؟', verbose_name='سفارش انجام شده ؟')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('carts', models.ManyToManyField(db_index=True, help_text='ایتم ها', to='card.cartitem', verbose_name='ایتم ها')),
                ('user', models.ForeignKey(blank=True, help_text='کاربر', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش ها',
                'verbose_name_plural': 'سفارش ها',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی پرداخت', primary_key=True, serialize=False, unique=True, verbose_name='ای دی پرداخت')),
                ('bank_status', models.CharField(db_index=True, help_text='(بانک) وضعیت پرداخت', max_length=150, verbose_name='(بانک) وضعیت پرداخت')),
                ('tracking_code', models.CharField(db_index=True, help_text='(بانک) tracking code', max_length=150, verbose_name='(بانک) tracking code')),
                ('bank_name', models.CharField(db_index=True, help_text='(بانک) درگاه پرداخت', max_length=150, verbose_name='(بانک) درگاه پرداخت')),
                ('amount', models.FloatField(db_index=True, help_text='مقدار پرداخت شده', verbose_name='مقدار پرداخت شده')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('status', models.CharField(blank=True, help_text='وضعیت', max_length=100, null=True, verbose_name='وضعیت')),
                ('user', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت ها',
                'verbose_name_plural': 'پرداخت ها',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='ای دی سفارش', primary_key=True, serialize=False, unique=True, verbose_name='ای دی سفارش')),
                ('quantity', models.PositiveIntegerField(db_index=True, help_text='تعداد', verbose_name='تعداد')),
                ('package_price', models.FloatField(db_index=True, help_text='قیمت پکیج', verbose_name='قیمت پکیج')),
                ('ordered', models.BooleanField(db_index=True, default=False, help_text='سفارش انجام شده', verbose_name='سفارش انجام شده')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='زمان ساخت', null=True, verbose_name='زمان ساخت')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, help_text='زمان ارتقا', null=True, verbose_name='زمان ارتقا')),
                ('category', models.ForeignKey(help_text='پکیج', on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='پکیج')),
                ('order', models.ForeignKey(blank=True, help_text='سفارش', null=True, on_delete=django.db.models.deletion.PROTECT, to='order.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(help_text='کاربر', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('payment', models.ForeignKey(blank=True, help_text='پرداخت', null=True, on_delete=django.db.models.deletion.PROTECT, to='order.payment', verbose_name='پرداخت')),
            ],
            options={
                'verbose_name': 'سفارشات پکیج',
                'verbose_name_plural': 'سفارشات پکیج',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, help_text='پرداخت', null=True, on_delete=django.db.models.deletion.PROTECT, to='order.payment', verbose_name='پرداخت'),
        ),
    ]
