# Generated by Django 5.0.1 on 2024-02-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_linl',
            field=models.URLField(blank=True, db_index=True, max_length=500, null=True),
        ),
    ]
